import os
import resend

resend.api_key = os.environ.get("RESEND_API_KEY", "")


async def send_audit_email(
    recipient_email: str,
    target_url: str,
    report_filepath: str,
    markdown_content: str,
):
  """Sends the generated audit report via Resend."""
  if not resend.api_key:
    print(
        "[Email Warning] RESEND_API_KEY environment variable is not set."
        " Skipping email dispatch."
    )
    return

  try:
    # Use your verified Resend domain sender address
    sender_email = os.environ.get("RESEND_FROM_EMAIL", "audit@trilloka.com")

    # Read markdown content for the email body summary
    preview_snippet = (
        markdown_content[:1500] + "..."
        if len(markdown_content) > 1500
        else markdown_content
    )

    params = {
        "from": sender_email,
        "to": [recipient_email],
        "subject": f"Your Trilloka Revenue Leak Audit Report: {target_url}",
        "html": (
            f"<h3>Revenue Audit Complete for {target_url}</h3>"
            "<p>Your comprehensive solution blueprint and gap analysis report"
            " has been successfully compiled.</p>"
            "<hr>"
            f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{preview_snippet}</pre>"
            "<hr>"
            "<p><i>Generated by Trilloka Revenue Readiness Engine.</i></p>"
        ),
    }

    response = resend.Emails.send(params)
    print(f"[Email Success] Report successfully sent to {recipient_email}")

  except Exception as e:
    print(
        f"[Email Error] Failed to dispatch audit email to {recipient_email}:"
        f" {str(e)}"
    )